// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(RadioContext))]
    partial class RadioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Employer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Core.ReclameBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<int>("Period");

                    b.Property<long>("ResponsibleId");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("ReclameBlocks");
                });

            modelBuilder.Entity("Core.Release", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Deleted");

                    b.Property<TimeSpan>("Duration");

                    b.Property<long>("LeadingId");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("ReclameBlockId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("LeadingId");

                    b.HasIndex("ReclameBlockId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Core.ReclameBlock", b =>
                {
                    b.HasOne("Core.Employer", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Release", b =>
                {
                    b.HasOne("Core.Employer", "Leading")
                        .WithMany()
                        .HasForeignKey("LeadingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.ReclameBlock", "ReclameBlock")
                        .WithMany("Releases")
                        .HasForeignKey("ReclameBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
